blank_issues_enabled: true
contact_links:
  - name: Website
    url: https://jonasbernard.github.io/FakeStandby/
    about: Before asking a question you can search for information on the project website.
